### ISSUE TITLE
Can't figure how to get it to work

### ISSUE THREAD

**Issue by xfzv** [alker0/chezmoi.vim#45] opened 2022-10-21 13:27 UTC
```
❯  nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
```

I'm using [wbthomason/packer.nvim](https://github.com/wbthomason/packer.nvim) to manage my plug-ins, including this one (loaded early, as suggested in the README:

https://github.com/alker0/chezmoi.vim/blob/7fd839d7fa275e7ffc4b11e2f1d99527c9024681/README.md?plain=1#L56

Relevant part of my `plugins.lua`:

```lua
vim.api.nvim_command('packadd packer.nvim')
function get_setup(name)
  return string.format('require("setup/%s")', name)
end

return require('packer').startup({
  function(use)
    use { 'wbthomason/packer.nvim' }
    use { 'lewis6991/impatient.nvim', config = get_setup('impatient') }
    use { 'alker0/chezmoi.vim', config = get_setup('chezmoi') }
-- ...
```

I'm using a custom source dir path for chezmoi, so I use:

```lua
-- ~/.config/nvim/lua/setup/chezmoi.lua
vim.cmd ([[ let g:chezmoi#source_dir_path = "~/dotfiles" ]])
```

This seems to work as expected:

![image](https://user-images.githubusercontent.com/78810647/197204585-029092b7-7cb8-4a52-94eb-e63e494ff75d.png)

However, I'm not getting any syntax highlighting at all. Here are various screenshots:

<details>
  <summary>Screenshots</summary>
  
- regular `~/.zshenv` (top) and `dot_zshenv` (bottom)
![image](https://user-images.githubusercontent.com/78810647/197205249-f8990d7a-7226-4e78-8773-70576c1ca13a.png)

- `.chezmoiignore` in source dir:
![image](https://user-images.githubusercontent.com/78810647/197206223-eadc65a9-b357-4082-9849-3ae7aaf7a2b5.png)

- After running `:set ft=chezmoitmpl` manually:
![image](https://user-images.githubusercontent.com/78810647/197206406-60b11a13-f456-4a32-adef-eca713d41787.png)

</details>

Not sure what I'm doing wrong, any advice is appreciated. Thanks!

---

Edit:

```vim
let chezmoi#_loaded
```

![image](https://user-images.githubusercontent.com/78810647/197218433-29a48605-d890-4fe5-a07b-d4a52f3704bb.png)

Is this normal? Not sure if it means `0` because `#` is treated as a comment or if it's actually `1` aka plug-in disabled.

**Comment by alker0** [comment] 2022-10-26 07:47
Hi. Thank you for your catching.

Missing highlighting in .chezmoi*.yml should be fixed by #47 (it has processed yaml but not yml before).

For highlighting `*.service.tmpl` correctly, it seems to need special adjustment for merging syntax `systemd` and `go-template`. I'll split it out as a new issue.

For `user-override.js.tmpl`, more details needed. Please tell the file path from your chezmoi's source directory if you don't mind.

For the core problem this issue that integration with `neovim`, `lua` and `packer`, I don't know how do combination and configuration of these affect ordering around file type detection yet. I don't use `neovim` and need to make time for making similar environment and reproduction. Please give me a few months to start once being free.

**Comment by alker0** [comment] 2022-11-11 10:17
Please update it and check if it enabled highlighting automatically for below files.
- `.chezmoiignore`
- `.chezmoiexternal.yml`
- `.chezmoi.yml.tmpl`
- `user-overrides.js.tmpl`

For passing options to this plugin in managed by packer, you need to define manually because both `setup =` and `config =` don't run before file type detection.
In packer settings, the `config =` option runs a script after loaded the plugin, and `setup =` does before but after file type detection, does it start to watch the plugin be going to load. `setup =` seems to focus to help you run scripts lazily rather than early for good at combining the plugin and a plugin-specific script and make it wait custom trigger together.

Please ask anything if you still get (excepting about `.service.tmpl` you can track in #48) , or close it.

**Comment by alker0** [comment] 2022-11-12 00:54
hmm...
What does running this show? This shows updated time and where packer installed it into, if using packer, it needs to be in `start/` , or `opt/` doesn't work.
```sh
# With bracket keeps your current directory
(cd ~/.local/share/nvim/site/pack/packer && stat -c "%n,%y" ./*/chezmoi.vim{,/*} | column -t -s,)
```
If it's in `opt/`, you need to reinstall this plugin manually via:
1. Comment out `use { 'alker0/chezmoi.vim' }`
2. Restart neovim and run `PackerSync`
3. Uncomment `use { 'alker0/chezmoi.vim' }`
4. Restart neovim and run `PackerSync`

By the way, for getting ordering of startup phases verbosely, you can run this.
```sh
echo > /tmp/foo.txt && nvim --startuptime /tmp/foo.txt ~/dotfiles/.chezmoi.yml.tmpl '+quit' && nvim /tmp/foo.txt
```
And it should show like (if succeeded):

<details><summary><code>/tmp/foo.txt</code></summary>
<pre><code>times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.005  000.005: --- NVIM STARTING ---
000.077  000.072: event init
000.169  000.092: ...MANY...
000.169  000.092: ...LINES...
003.479  000.059  000.059: sourcing /usr/share/nvim/runtime/ftplugin.vim
003.545  000.032  000.032: sourcing /usr/share/nvim/runtime/indent.vim
005.048  000.148  000.148: require('packer.XXX')
005.048  000.148  000.148: ...MANY...
005.048  000.148  000.148: ...LINES...
006.362  002.781  000.147: sourcing /home/alker/.config/nvim/init.lua
006.367  000.589: sourcing vimrc file(s)
=================================== Ordering of some lines below is the most important. =========================
006.627  000.230  000.230: sourcing /home/alker/.local/share/nvim/site/pack/packer/start/chezmoi.vim/filetype.vim
006.857  000.187  000.187: sourcing /usr/share/nvim/runtime/filetype.lua
007.048  000.097  000.097: sourcing /usr/share/nvim/runtime/syntax/synload.vim
007.207  000.305  000.208: sourcing /usr/share/nvim/runtime/syntax/syntax.vim
007.867  000.282  000.282: ...MANY...
007.867  000.282  000.282: ...LINES...
009.954  000.238  000.238: require('setup/impatient')
009.956  000.423  000.185: sourcing /home/alker/.config/nvim/plugin/packer_compiled.lua
010.097  000.040  000.040: sourcing /usr/share/nvim/runtime/plugin/man.lua
010.105  000.779: ...SOME...
010.105  000.779: ...LINES...
011.044  000.807: reading ShaDa
011.406  000.119  000.119: sourcing /home/alker/.local/share/nvim/site/pack/packer/start/chezmoi.vim/autoload/chezmoi/filetype.vim
012.259  000.709  000.709: require('vim.filetype')
012.797  000.040  000.040: sourcing /usr/share/nvim/runtime/ftplugin/yaml.vim
013.283  000.114  000.114: sourcing /usr/share/nvim/runtime/indent/yaml.vim
014.052  000.669  000.669: sourcing /usr/share/nvim/runtime/syntax/yaml.vim
014.305  000.033  000.033: sourcing /usr/share/nvim/runtime/ftplugin/yaml.vim
015.026  000.017  000.017: sourcing /usr/share/nvim/runtime/indent/yaml.vim
015.749  000.581  000.581: sourcing /usr/share/nvim/runtime/syntax/yaml.vim
016.053  000.148  000.148: sourcing /home/alker/.local/share/nvim/site/pack/packer/start/chezmoi.vim/vendor/vim-go/syntax/gotmpl.vim
016.055  000.162  000.014: sourcing /home/alker/.local/share/nvim/site/pack/packer/start/chezmoi.vim/syntax/gotmpl.vim
016.099  000.239  000.077: sourcing /home/alker/.local/share/nvim/site/pack/packer/start/chezmoi.vim/syntax/chezmoitmpl.vim
016.511  002.947: opening buffers
016.525  000.015: BufEnter autocommands
016.527  000.002: editing files in windows
</code></pre>
</details>

**Comment by alker0** [comment] 2022-11-13 03:25
Please try the latest and re-check if it works.
But it might not do for `.chezmoiignore`, and if so, please run these and tell the output.
- `:set filetype`
- `:echo substitute(execute('let'), '\n\%(b:chezmoi_\|b:current_syntax\)\@![^\n]*', '', 'g')`

**Comment by alker0** [comment] 2022-11-14 12:06
My neovim environment still doesn't reproduce the issue so I don't sure this comes from.

`nvim --version` shows:
```sh
NVIM v0.8.0-1210-gd367ed9b2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az505-656

Features: +acl +iconv +tui
```
In `~/.config/nvim/lua/plugins.lua`:
![plugin-lua](https://user-images.githubusercontent.com/51204827/201646047-51e0992f-ba11-4675-b8b4-eb2f87fc74cc.png)

In `~/dotfiles/test-sh.toml` and `~/dotfiles/test-yaml.toml`:
![test-sh](https://user-images.githubusercontent.com/51204827/201645710-279ffa6f-6c62-4211-a695-5bfb2d047322.png)
![test-yaml](https://user-images.githubusercontent.com/51204827/201645711-7e985109-5973-4452-ad4c-637816a627f5.png)

This may come from integration with others.
Please try toggling On/Off each plugins (e.g. with `disabled` of packer option) and tell whether any works correctly.

**Closed as completed** 2022-11-14 17:13 UTC

**Comment by alker0** [comment] 2022-11-16 04:25
Yes! :tada: I'm glad I could help you and also fix and improve it. Thank you for a lot of time and response for my many questions.
